sudo: false
language: node_js
node_js:
  - "0.12"

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH=$PATH:$HOME/.meteor

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b6725f450c497ac5b2d0
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
